-- Additive SFA/DMS schema. This creates new tables only; it never alters
-- existing ERP tables. Apply in a reviewed production deployment window.
CREATE TABLE IF NOT EXISTS sfa_territories (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, code varchar NOT NULL, name varchar NOT NULL, division varchar, district varchar, active boolean NOT NULL DEFAULT true, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", code));
CREATE TABLE IF NOT EXISTS dms_distributors (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, code varchar NOT NULL, name varchar NOT NULL, "territoryId" varchar, "warehouseId" varchar, "contactName" varchar, phone varchar, "creditLimit" numeric(14,2) NOT NULL DEFAULT 0, active boolean NOT NULL DEFAULT true, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", code));
CREATE TABLE IF NOT EXISTS dms_retailers (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, code varchar NOT NULL, name varchar NOT NULL, "distributorId" varchar, "territoryId" varchar, "ownerName" varchar, phone varchar, address text, latitude numeric(10,7), longitude numeric(10,7), active boolean NOT NULL DEFAULT true, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", code));
CREATE TABLE IF NOT EXISTS sfa_routes (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, code varchar NOT NULL, name varchar NOT NULL, "territoryId" varchar, "assignedUserId" varchar, "visitDay" varchar, active boolean NOT NULL DEFAULT true, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", code));
CREATE TABLE IF NOT EXISTS sfa_field_visits (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, "retailerId" varchar NOT NULL, "distributorId" varchar, "routeId" varchar, "salesRepId" varchar NOT NULL, "visitDate" date NOT NULL, "checkInAt" timestamp, "checkOutAt" timestamp, "checkInLatitude" numeric(10,7), "checkInLongitude" numeric(10,7), status varchar NOT NULL DEFAULT 'Planned', note text, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS dms_sales_orders (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, "orderNumber" varchar NOT NULL, "retailerId" varchar NOT NULL, "distributorId" varchar, "territoryId" varchar, "salesRepId" varchar NOT NULL, "orderDate" date NOT NULL, status varchar NOT NULL DEFAULT 'Draft', "grossAmount" numeric(14,2) NOT NULL DEFAULT 0, "discountAmount" numeric(14,2) NOT NULL DEFAULT 0, "netAmount" numeric(14,2) NOT NULL DEFAULT 0, note text, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", "orderNumber"));
CREATE TABLE IF NOT EXISTS dms_sales_order_items (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, "orderId" uuid NOT NULL, "productId" uuid NOT NULL, quantity int NOT NULL, "unitPrice" numeric(14,2) NOT NULL, "discountAmount" numeric(14,2) NOT NULL DEFAULT 0, "lineTotal" numeric(14,2) NOT NULL, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("orderId", "productId"));
CREATE TABLE IF NOT EXISTS sfa_collections (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, "retailerId" varchar NOT NULL, "distributorId" varchar, "salesRepId" varchar NOT NULL, "collectionDate" date NOT NULL, amount numeric(14,2) NOT NULL, "paymentMethod" varchar NOT NULL, "referenceNumber" varchar, status varchar NOT NULL DEFAULT 'Submitted', note text, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP);
CREATE TABLE IF NOT EXISTS sfa_sales_targets (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), "organizationId" uuid NOT NULL, "salesRepId" varchar NOT NULL, period varchar NOT NULL, "salesTarget" numeric(14,2) NOT NULL, "collectionTarget" numeric(14,2) NOT NULL DEFAULT 0, "visitTarget" int NOT NULL DEFAULT 0, "createdAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, "updatedAt" timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP, UNIQUE ("organizationId", "salesRepId", period));
CREATE INDEX IF NOT EXISTS idx_sfa_visits_org_date ON sfa_field_visits ("organizationId", "visitDate");
CREATE INDEX IF NOT EXISTS idx_dms_orders_org_date ON dms_sales_orders ("organizationId", "orderDate");
CREATE INDEX IF NOT EXISTS idx_sfa_collections_org_date ON sfa_collections ("organizationId", "collectionDate");
